[colors.primary]
foreground = "#319b9b"
background = "#e1f6f6"
dim_foreground = "#7bb5b5"
bright_foreground = "#319b9b"

[colors.cursor]
foreground = "#319b9b"
cursor = "#9ab8b8"

[colors.vi_mode_cursor]
foreground = "#319b9b"
cursor = "#9ab8b8"

[colors.search.matches]
foreground = "#7bb5b5"
background = "#d6efef"

[colors.search.focused_match]
foreground = "#e1f6f6"
background = "#000000"

[colors.hints.start]
foreground = "#7bb5b5"
background = "#e0f6f6"

[colors.hints.end]
foreground = "#abcccc"
background = "#e0f6f6"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#319b9b"
background = "#e0f6f6"

[colors.selection]
text = "#319b9b"
background = "#b2d6d6"

[colors.normal]
black   = "#ffffff"  # Adjusted to match a darker shade of your background
red     = "#b4637a"  # Same as Rose Pine Dawn
green   = "#7bb5b5"  # Match to your existing greenish shade
yellow  = "#9ab8b8"  # Adjusted to fit within the monochrome palette
blue    = "#8cbfbd"  # Slightly darker shade of your cyan
magenta = "#8cbfbd"  # Similar to blue to maintain the monochrome effect
cyan    = "#7bb5b5"  # Same as green for consistency
white   = "#e1f6f6"  # Same as your existing foreground

[colors.bright]
black   = "#7bb5b5"  # Slightly lighter than the normal black
red     = "#b4637a"  # Same as Rose Pine Dawn
green   = "#7bb5b5"  # Match to your existing greenish shade
yellow  = "#9ab8b8"  # Adjusted to fit within the monochrome palette
blue    = "#8cbfbd"  # Slightly darker shade of your cyan
magenta = "#8cbfbd"  # Similar to blue to maintain the monochrome effect
cyan    = "#7bb5b5"  # Same as green for consistency
white   = "#e1f6f6"  # Same as your existing foreground

[colors.dim]
black   = "#7bb5b5"  # Slightly lighter than the normal black
red     = "#b4637a"  # Same as Rose Pine Dawn
green   = "#7bb5b5"  # Match to your existing greenish shade
yellow  = "#9ab8b8"  # Adjusted to fit within the monochrome palette
blue    = "#8cbfbd"  # Slightly darker shade of your cyan
magenta = "#8cbfbd"  # Similar to blue to maintain the monochrome effect
cyan    = "#7bb5b5"  # Same as green for consistency
white   = "#e1f6f6"  # Same as your existing foreground


